name: Sign and Verify JavaScript File

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up OpenSSL
      run: |
        sudo apt-get update
        sudo apt-get install -y openssl

    - name: Generate key and certificate (for demonstration purposes; use a real key in production)
      run: |
        openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj "/CN=example.com"
        openssl x509 -in cert.pem -pubkey -noout -out pubkey.pem
      shell: bash

    - name: Show generated files
      run: |
        ls -la
        cat cert.pem
        cat pubkey.pem
      shell: bash

    - name: Sign JavaScript file
      run: |
        openssl dgst -sha256 -sign key.pem -out signature.bin build.js
      shell: bash

    - name: Show signature
      run: cat signature.bin
      shell: bash

    - name: Verify signature
      run: |
        openssl dgst -sha256 -verify pubkey.pem -signature signature.bin build.js
      shell: bash

    - name: Upload signed file and signature
      uses: actions/upload-artifact@v2
      with:
        name: signed-code
        path: |
          build.js
          signature.bin
