name: Build and Sign Executable

on: [push]

jobs:
  build-and-sign:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build executable
      run: npm run build

    - name: Set up OpenSSL
      run: |
        sudo apt-get update
        sudo apt-get install -y openssl

    - name: Generate key and certificate (for demonstration purposes; use a real key in production)
      run: |
        openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj "/CN=multicube.fr"
        openssl x509 -in cert.pem -pubkey -noout -out pubkey.pem

    - name: Sign the executable
      run: |
        openssl dgst -sha256 -sign key.pem -out executable.sig /src/app.js

    - name: Verify the signature
      run: |
        openssl dgst -sha256 -verify pubkey.pem -signature executable.sig /src/app.js

    - name: Upload signed executable and signature
      uses: actions/upload-artifact@v2
      with:
        name: signed-executable
        path: |
          /src/app.js
          executable.sig
