name: Launcher Build with Signing and Verification

on:
  push:
    branches: [ master ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_ENV
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: Release ${{ env.version }}
          draft: false
          prerelease: ${{ contains(env.version, 'beta') || contains(env.version, 'alpha') }}

  build-launcher:
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: npm run build
        shell: bash

      # Conditions pour les étapes spécifiques à l'OS
      - name: Set up OpenSSL (Ubuntu and macOS)
        if: matrix.os != 'windows-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y openssl
        shell: bash

      - name: Generate key and certificate (for demonstration purposes; use a real key in production)
        run: |
          openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj "/CN=multicube.fr"
          openssl x509 -in cert.pem -pubkey -noout -out pubkey.pem
        shell: bash

      - name: Sign the build (Ubuntu and macOS)
        if: matrix.os != 'windows-latest'
        run: |
          openssl dgst -sha256 -sign key.pem -out signature.bin build.js
        shell: bash

      - name: Verify the signature (Ubuntu and macOS)
        if: matrix.os != 'windows-latest'
        run: |
          openssl dgst -sha256 -verify pubkey.pem -signature signature.bin build.js
        shell: bash

      - name: Upload signed build and signature
        uses: actions/upload-artifact@v2
        with:
          name: signed-launcher
          path: |
            build.js
            signature.bin
